---
abstract: 'control concurrency of asynchronous tasks'
author:
  - 'Toshio Ito <debug.ito@gmail.com>'
build_requires:
  FindBin: 0
  Test::Builder: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Async-Queue
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Scalar::Util: 0
version: 0.02
